### ISSUE TITLE
rlimit_files must be a kind of Integer

### ISSUE THREAD

**Issue by corycomer** [stajkowski/php5-fpm#7]
Getting this when using the LWRP to setup a new pool. This is on Ubuntu 14.04 with Chef 11.10 

```
Chef::Exceptions::ValidationFailed
       ----------------------------------
       Option rlimit_files must be a kind of Integer!  You passed "1024".
```

Here's what is in my recipe:

```
include_recipe 'php5-fpm::install'

php5_fpm_pool 'www' do
  use_sockets true
  auto_calculate true
  percent_share 80
  round_down true
  pm_status_path "/php5-fpm-status"
  action :create
  notifies :restart, "service[#{node["php_fpm"]["package"]}]"
end
```

Here's the stacktrace from the failed kitchen converge

```
       ================================================================================
       Error executing action `create` on resource 'php5-fpm_pool[www]'
       ================================================================================
       
       Chef::Exceptions::ValidationFailed
       ----------------------------------
       Option rlimit_files must be a kind of Integer!  You passed "1024".
       
       Cookbook Trace:
       ---------------
       /tmp/kitchen/cache/cookbooks/php5-fpm/providers/pool.rb:188:in `block (2 levels) in load_current_resource'
       /tmp/kitchen/cache/cookbooks/php5-fpm/providers/pool.rb:128:in `each_line'
       /tmp/kitchen/cache/cookbooks/php5-fpm/providers/pool.rb:128:in `block in load_current_resource'
       /tmp/kitchen/cache/cookbooks/php5-fpm/providers/pool.rb:125:in `open'
       /tmp/kitchen/cache/cookbooks/php5-fpm/providers/pool.rb:125:in `load_current_resource'
       
       Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/my-php5-fpm/recipes/default.rb
       
        11: php5_fpm_pool 'www' do
        12:   rlimit_files nil
        13:   use_sockets true
        14:   auto_calculate true
        15:   percent_share 80
        16:   round_down true
        17:   pm_status_path "/php5-fpm-status"
        18:   ping_path "/php5-fpm-ping"
        19:   ping_response "/php5-fpm-response"
        20:   action :create
        21:   notifies :restart, "service[#{node["php_fpm"]["package"]}]"
        22: end
       
       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/my-php5-fpm/recipes/default.rb:11:in `from_file'
       
       php5_fpm_pool("www") do
         action [:create]
         retries 0
         retry_delay 2
         cookbook_name "my-php5-fpm"
         recipe_name "default"
         use_sockets true
         auto_calculate true
         percent_share 80
         round_down true
         pm_status_path "/php5-fpm-status"
         ping_path "/php5-fpm-ping"
         ping_response "/php5-fpm-response"
         pool_name "www"
         pool_user "www-data"
         pool_group "www-data"
         listen_address "127.0.0.1"
         listen_port 9000
         listen_backlog "65536"
         pm "dynamic"
         pm_max_children 10
         pm_start_servers 4
         pm_min_spare_servers 2
         pm_max_spare_servers 6
         pm_process_idle_timeout "10s"
         pm_max_requests 0
         access_format "%R - %u %t \\\"%m %r\\\" %s"
         request_slowlog_timeout 0
         request_terminate_timeout 0
         chdir "/"
         catch_workers_output "no"
         security_limit_extensions ".php"
       end
       
       
       Running handlers:
       [2015-02-17T06:25:15+00:00] ERROR: Running exception handlers
       
       [2015-02-17T06:25:15+00:00] ERROR: Exception handlers complete
       
       Chef Client failed. 0 resources updated in 0.544687613 seconds
       [2015-02-17T06:25:15+00:00] ERROR: php5-fpm_pool[www] (my-php5-fpm::default line 11) had an error: Chef::Exceptions::ValidationFailed: Option rlimit_files must be a kind of Integer!  You passed "1024".
       [2015-02-17T06:25:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-ubuntu-1404>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /tmp/kitchen/dna.json
']
>>>>>> ----------------------
```

**Comment by stajkowski** [comment]
Strange, did you state rlimit to "1024" as I don't see it in the configuration shared?

**Comment by corycomer** [comment]
I think the value is coming from the default /etc/php5/fpm/pool.d/www.conf:322 
```
; Set open file descriptor rlimit.
; Default Value: system defined value
;rlimit_files = 1024
```
When the pool resource loads the default pool config and merges the existing attributes into the resource, the validation fails. 

https://github.com/stajkowski/php5-fpm/blob/master/providers/pool.rb#L188
```
 configuration_exists(fline,"rlimit_files =") ? @current_resource.rlimit_files(lstring.chomp.strip) : nil
```

It looks like the constraint for the attribute is Integer but it's getting a String from the strip

https://github.com/stajkowski/php5-fpm/blob/master/resources/pool.rb#L49
```
attribute :rlimit_files, :kind_of => Integer, :required => false, :default => nil
```

A couple of the other attributes look like they explicitly convert to an Integer, 

https://github.com/stajkowski/php5-fpm/blob/master/providers/pool.rb#L178
```
 configuration_exists(fline,"request_slowlog_timeout =") ? @current_resource.request_slowlog_timeout(lstring.chomp.strip.to_i) : nil
```

I'm a bit wrapped up at the moment, but if you're not able to have a look, I can try and have a look at getting a test/PR for this later. Thanks for the quick follow up!

**Comment by stajkowski** [comment]
Yep you are right, it's coming from the default file and loading in the current resource. I'll fix this tonight, just need to go through each attribute and convert the incoming value to Integer for those that need it.  Thanks for looking into this!
