### ISSUE TITLE
Error using php5_fpm_pool

### ISSUE THREAD

**Issue by codedbypaul** [stajkowski/php5-fpm#8]
I'm running into difficulty using php5_fpm_pool.
```
Chef::Exceptions::ValidationFailed
    ----------------------------------
    Option listen_address's value /var/run/phpfpm_example.sock does not match regular expression /\A((?x-mi:0
                   |1(?:[0-9][0-9]?)?
                   |2(?:[0-4][0-9]?|5[0-5]?|[6-9])?
                   |[3-9][0-9]?))\.((?x-mi:0
                   |1(?:[0-9][0-9]?)?
                   |2(?:[0-4][0-9]?|5[0-5]?|[6-9])?
                   |[3-9][0-9]?))\.((?x-mi:0
                   |1(?:[0-9][0-9]?)?
                   |2(?:[0-4][0-9]?|5[0-5]?|[6-9])?
                   |[3-9][0-9]?))\.((?x-mi:0
                   |1(?:[0-9][0-9]?)?
                   |2(?:[0-4][0-9]?|5[0-5]?|[6-9])?
                   |[3-9][0-9]?))\z/
```
Here's what i'm using in my recipe:
```
include_recipe "php5-fpm::install"

php5_fpm_pool "www" 
```
Here's the stacktrace:
```
Cookbook Trace:
    ---------------
    /vagrant/cookbooks/php5-fpm/providers/pool.rb:149:in `block (2 levels) in load_current_resource'
    /vagrant/cookbooks/php5-fpm/providers/pool.rb:128:in `each_line'
    /vagrant/cookbooks/php5-fpm/providers/pool.rb:128:in `block in load_current_resource'
    /vagrant/cookbooks/php5-fpm/providers/pool.rb:125:in `open'
    /vagrant/cookbooks/php5-fpm/providers/pool.rb:125:in `load_current_resource'
    
    Resource Declaration:
    ---------------------
    # In /vagrant/cookbooks/dev/recipes/default.rb
    
     35: php5_fpm_pool "www" 
     36: 
    
    Compiled Resource:
    ------------------
    # Declared in /vagrant/cookbooks/dev/recipes/default.rb:35:in `from_file'
    
    php5_fpm_pool("www") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :php5_fpm_pool
      cookbook_name :dev
      recipe_name "default"
      pool_name "www"
      pool_user "www-data"
      pool_group "www-data"
      listen_address "127.0.0.1"
      listen_port 9000
      listen_backlog "65536"
      pm "dynamic"
      pm_max_children 10
      pm_start_servers 4
      pm_min_spare_servers 2
      pm_max_spare_servers 6
      pm_process_idle_timeout "10s"
      pm_max_requests 0
      pm_status_path "/status"
      ping_path "/ping"
      ping_response "/pong"
      access_format "%R - %u %t \\\"%m %r\\\" %s"
      request_slowlog_timeout 0
      request_terminate_timeout 0
      chdir "/"
      catch_workers_output "no"
      security_limit_extensions ".php"
      percent_share 100
    end
```
I"m guessing it due to this in the default www.conf file?
```
; The address on which to accept FastCGI requests.
; Valid syntaxes are:
;   'ip.add.re.ss:port'    - to listen on a TCP socket to a specific address on
;                            a specific port;
;   'port'                 - to listen on a TCP socket to all addresses on a
;                            specific port;
;   '/path/to/unix/socket' - to listen on a unix socket.
; Note: This value is mandatory.
listen = /var/run/php5-fpm.sock
```

**Comment by stajkowski** [comment]
Hey there, thanks for posting.  Yeah from this I can tell this is from the www default configuration picking up the listen parameter and trying to put it into the listen address resource parameter, which does a check to see if it is a valid ip address.

I'll probably put in a check for the listen parameter on load_current_resource to tell if we are using sockets or not.  Thanks for posting and I should be able to get this fixed this afternoon.

**Comment by codedbypaul** [comment]
Thanks for that. :+1:

**Comment by stajkowski** [comment]
All set to go on 4.4.  Keep in mind that you must use 'overwrite true' or 'action :modify' to alter an existing configuration.  Typically it is good just to use overwrite true.
